In [1]:
import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

In [2]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.shape

(768, 9)

In [4]:
X=df.drop('Outcome', axis=1)
y=df['Outcome']

In [5]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=2)

In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [8]:
y_score=lr.predict_proba(X_test)[:,1]

In [9]:
y_score

array([0.04958272, 0.17465237, 0.09371421, 0.25498527, 0.63544411,
       0.11678983, 0.06572494, 0.42205853, 0.04868306, 0.57573471,
       0.33863625, 0.41291883, 0.69856381, 0.19977266, 0.02001746,
       0.82464796, 0.86664921, 0.03103935, 0.25520533, 0.89482967,
       0.9524128 , 0.83473982, 0.11748196, 0.44680101, 0.08928928,
       0.06884734, 0.65103197, 0.41203571, 0.17868607, 0.28700518,
       0.24541223, 0.43890867, 0.00943736, 0.24270891, 0.35158355,
       0.96162578, 0.34370878, 0.80921868, 0.29388299, 0.0508959 ,
       0.18197679, 0.08679044, 0.42227371, 0.18747253, 0.03014455,
       0.03952653, 0.24753785, 0.42775062, 0.1053518 , 0.3798344 ,
       0.99355352, 0.10657157, 0.39080959, 0.76883256, 0.36868927,
       0.45776033, 0.95031684, 0.41977042, 0.3912647 , 0.04380499,
       0.37302653, 0.90120096, 0.88174707, 0.8884191 , 0.33097803,
       0.06925511, 0.95263699, 0.20064604, 0.26064162, 0.35456865,
       0.10364028, 0.08174189, 0.45048175, 0.09221197, 0.08653

In [10]:
from sklearn.metrics import roc_curve
fpr, tpr, threshold=roc_curve(y_test,y_score)

In [11]:
threshold

array([1.99355352e+00, 9.93553524e-01, 9.52636989e-01, 9.52412800e-01,
       8.24647963e-01, 7.68832558e-01, 7.61870153e-01, 6.83608317e-01,
       6.75298794e-01, 6.74141114e-01, 6.51031975e-01, 6.50914772e-01,
       6.35444105e-01, 5.86185106e-01, 5.75734713e-01, 5.69376056e-01,
       5.24903707e-01, 4.70306042e-01, 4.61251228e-01, 4.50481747e-01,
       4.38908668e-01, 4.38738369e-01, 4.22273714e-01, 4.19770425e-01,
       4.12918835e-01, 4.12035711e-01, 4.04861763e-01, 3.79834403e-01,
       3.68689274e-01, 3.10059358e-01, 3.08867605e-01, 2.77861570e-01,
       2.72133103e-01, 2.55205326e-01, 2.54985273e-01, 2.47537855e-01,
       2.45412234e-01, 2.36585988e-01, 2.28957934e-01, 1.81976787e-01,
       1.78686072e-01, 1.74652372e-01, 1.73268087e-01, 1.46386470e-01,
       1.40822435e-01, 1.16789832e-01, 1.15001733e-01, 1.10087021e-01,
       1.06571572e-01, 8.92892793e-02, 8.67904417e-02, 2.00174635e-02,
       1.93152916e-02, 1.60987241e-03])

In [12]:
fpr

array([0.        , 0.        , 0.        , 0.00917431, 0.00917431,
       0.02752294, 0.02752294, 0.0733945 , 0.0733945 , 0.08256881,
       0.08256881, 0.09174312, 0.09174312, 0.10091743, 0.10091743,
       0.11009174, 0.11009174, 0.12844037, 0.12844037, 0.14678899,
       0.14678899, 0.1559633 , 0.1559633 , 0.17431193, 0.17431193,
       0.18348624, 0.18348624, 0.22018349, 0.22018349, 0.30275229,
       0.30275229, 0.35779817, 0.35779817, 0.39449541, 0.39449541,
       0.40366972, 0.40366972, 0.42201835, 0.42201835, 0.53211009,
       0.53211009, 0.5412844 , 0.5412844 , 0.57798165, 0.57798165,
       0.63302752, 0.63302752, 0.66055046, 0.66055046, 0.74311927,
       0.74311927, 0.98165138, 0.98165138, 1.        ])

In [13]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

In [14]:
trace0

Scatter({
    'mode': 'lines',
    'name': 'ROC curve',
    'x': array([0.        , 0.        , 0.        , 0.00917431, 0.00917431, 0.02752294,
                0.02752294, 0.0733945 , 0.0733945 , 0.08256881, 0.08256881, 0.09174312,
                0.09174312, 0.10091743, 0.10091743, 0.11009174, 0.11009174, 0.12844037,
                0.12844037, 0.14678899, 0.14678899, 0.1559633 , 0.1559633 , 0.17431193,
                0.17431193, 0.18348624, 0.18348624, 0.22018349, 0.22018349, 0.30275229,
                0.30275229, 0.35779817, 0.35779817, 0.39449541, 0.39449541, 0.40366972,
                0.40366972, 0.42201835, 0.42201835, 0.53211009, 0.53211009, 0.5412844 ,
                0.5412844 , 0.57798165, 0.57798165, 0.63302752, 0.63302752, 0.66055046,
                0.66055046, 0.74311927, 0.74311927, 0.98165138, 0.98165138, 1.        ]),
    'y': array([0.        , 0.02222222, 0.08888889, 0.08888889, 0.28888889, 0.28888889,
                0.31111111, 0.31111111, 0.33333333, 0.33333333

In [15]:
# Only label every nth point to avoid cluttering
n = 10  
indices = np.arange(len(threshold)) % n == 0  # Choose indices where index mod n is 0
trace1 = go.Scatter(
    x=fpr[indices], 
    y=tpr[indices], 
    mode='markers+text', 
    name='Threshold points', 
    text=[f"Thr={thr:.2f}" for thr in threshold[indices]], 
    textposition='top center'
)
# Diagonal line
trace2 = go.Scatter(
    x=[0, 1], 
    y=[0, 1], 
    mode='lines', 
    name='Random (Area = 0.5)', 
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]
# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()



In [16]:
# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = threshold[optimal_idx]
print("Optimal threshold is:", optimal_threshold)

Optimal threshold is: 0.36868927400841833


In [17]:
import plotly.graph_objects as go
import numpy as np
from sklearn.metrics import roc_auc_score

# Assuming fpr, tpr, thresholds are already calculated as before
fpr, tpr, thresholds = roc_curve(y_test, y_score)

# Calculate the AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_score)

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name=f'ROC curve (Area = {roc_auc:.2f})'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices], 
    y=tpr[indices], 
    mode='markers+text', 
    name='Threshold points', 
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]], 
    textposition='top center'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1], 
    y=[0, 1], 
    mode='lines', 
    name='Random (Area = 0.5)', 
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [18]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Assuming that X_train, X_test, y_train, y_test are already defined

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1], 
    y=[0, 1], 
    mode='lines', 
    name='Random (Area = 0.5)', 
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()
